comment: off

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.50
        base: auto
    patch: off
ignore:
  - "tests/"
  - "notebooks/"
  - "*/__init.py"
  
