# .readthedocs.yml

build:
  image: latest

python:
  version: 3.6
  setup_py_install: true
  use_system_site_packages: false
  
requirements_file: docs/requirements.txt

# Build PDF & ePub
formats: []
